app: your-app
org: your-serverless-account

service: myserverlessproject

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: my-serverless-project-bucket-123123
      localDir: UploadData

functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-serverless-project-bucket-123123